adding DAST.

diff --git a/.github/workflows/container-image-sign.yml b/.github/workflows/container-image-sign.yml
--- a/.github/workflows/container-image-sign.yml
+++ b/.github/workflows/container-image-sign.yml
@@ -33,37 +33,37 @@ jobs:
         run: |
           docker build -t $REGISTRY/$IMAGE_NAME:$IMAGE_TAG .
 
-      - name: Install Snyk CLI
-        run: npm install -g snyk
+      # - name: Install Snyk CLI
+      #   run: npm install -g snyk
 
-      - name: Snyk Container Scan
-        id: snyk_container_scan
-        run: |
-          snyk container test --org=ekene95 --tags=dev,container  $REGISTRY/$IMAGE_NAME:$IMAGE_TAG --severity-threshold=medium
-        env:
-          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
-        continue-on-error: true
+      # - name: Snyk Container Scan
+      #   id: snyk_container_scan
+      #   run: |
+      #     snyk container test --org=ekene95 --tags=dev,container  $REGISTRY/$IMAGE_NAME:$IMAGE_TAG --severity-threshold=medium
+      #   env:
+      #     SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
+      #   continue-on-error: true
 
-      - name: Snyk Container Monitor
-        run: |
-          snyk container monitor $REGISTRY/$IMAGE_NAME:$IMAGE_TAG \
-            --org=ekene95 \
-            --project-name="$IMAGE_NAME:$IMAGE_TAG"
-        env:
-          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
+      # - name: Snyk Container Monitor
+      #   run: |
+      #     snyk container monitor $REGISTRY/$IMAGE_NAME:$IMAGE_TAG \
+      #       --org=ekene95 \
+      #       --project-name="$IMAGE_NAME:$IMAGE_TAG"
+      #   env:
+      #     SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
 
-      - name: Upload Snyk Results
-        uses: actions/upload-artifact@v4
-        if: always()
-        with:
-          name: snyk-results
-          path: snyk_results.json
+      # - name: Upload Snyk Results
+      #   uses: actions/upload-artifact@v4
+      #   if: always()
+      #   with:
+      #     name: snyk-results
+      #     path: snyk_results.json
 
-      - name: Fail Build on Snyk Vulnerabilities
-        if: steps.snyk_container_scan.outcome == 'failure'
-        run: |
-          echo "Snyk found vulnerabilities in the container image!"
-          exit 1
+      # - name: Fail Build on Snyk Vulnerabilities
+      #   if: steps.snyk_container_scan.outcome == 'failure'
+      #   run: |
+      #     echo "Snyk found vulnerabilities in the container image!"
+      #     exit 1
 
       - name: Install Cosign
         uses: sigstore/cosign-installer@main
@@ -88,3 +88,21 @@ jobs:
         run: |
           cosign verify --key env://COSIGN_PUBLIC_KEY $REGISTRY/$IMAGE_NAME@$DIGEST
 
+      - name: Run ZAP Scan
+        env:
+          DEV_URL: https://6832-105-113-78-20.ngrok-free.app  # Set this secret to your Ngrok URL
+        run: |
+          docker run --rm \
+            -v $(pwd):/zap/reports \
+            zaproxy/zap-stable zap-baseline.py \
+            -t $DEV_URL \
+            -r zap-report.html \
+            -x report.xml
+          
+      - name: Upload Report
+        uses: actions/upload-artifact@v4
+        with:
+          name: zap-results
+          path: |
+            zap-report.html
+            report.xml
