Security workflow end to end

diff --git a/.github/workflows/dev-workflow.yaml b/.github/workflows/dev-workflow.yaml
--- a/.github/workflows/dev-workflow.yaml
+++ b/.github/workflows/dev-workflow.yaml
@@ -1,20 +1,18 @@
-name: Parallel Build, Scan, Sign, Push, Deploy (develop only)
+ame: Build, Image Scan, Sign, Push Docker Image, Deploy and Scan post deployment (develop only)
 
 on:
   push:
     branches:
-      - develop
+#      - develop
 
 env:
   REGISTRY: docker.io
   IMAGE_NAME: kenzman/provenance
 
 jobs:
-  setup:
+  build-sign-push:
     runs-on: ubuntu-latest
-    outputs:
-      image_tag: ${{ env.IMAGE_TAG }}
-      digest: ${{ env.DIGEST }}
+
     steps:
       - name: Checkout code
         uses: actions/checkout@v3
@@ -30,109 +28,50 @@ jobs:
 
       - name: Log in to Docker Hub
         run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
-
-      - name: Build and Push Docker image
-        id: build
-        run: |
-          docker build -t $REGISTRY/$IMAGE_NAME:$IMAGE_TAG .
-          docker push $REGISTRY/$IMAGE_NAME:$IMAGE_TAG
-          # Extract digest (format: sha256:abc123...)
-          DIGEST=$(docker inspect --format='{{index .RepoDigests 0}}' $REGISTRY/$IMAGE_NAME:$IMAGE_TAG | cut -d'@' -f2)
-          echo "DIGEST=${DIGEST}" >> $GITHUB_ENV
-
-  security-scans:
-    needs: setup
-    runs-on: ubuntu-latest
-    strategy:
-      matrix:
-        scan_type: [sca, sast, container]
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v3
-
+        
+     #Snyk SAST & SCA starts here   
       - name: Install Snyk CLI
         run: npm install -g snyk
 
-      - name: Run Snyk Scans
-        id: snyk_scan
+      - name: Run Snyk SCA Scan
+        id: snyk_test
         run: |
-          case "${{ matrix.scan_type }}" in
-            sca)
-              mvn -N io.takari:maven:wrapper
-              snyk test --all-projects -org=ekene95 --severity-threshold=high
-              ;;
-            sast)
-              snyk code test --all-projects -org=ekene95 --severity-threshold=high
-              ;;
-            container)
-              snyk container test --org=ekene95 --tags=dev,container $REGISTRY/$IMAGE_NAME:${{ needs.setup.outputs.image_tag }} --severity-threshold=high
-              ;;
-          esac
+          mvn -N io.takari:maven:wrapper
+          snyk test --all-projects -org=ekene95 --severity-threshold=high
+        continue-on-error: true
+
+      - name: Run Snyk SAST Scan.
+        id: snyk_code_test
+        run: |
+          snyk code test --all-projects -org=ekene95 --severity-threshold=high
+        continue-on-error: true        
+
+      - name: Build Docker image
+        run: |
+          docker build -t $REGISTRY/$IMAGE_NAME:$IMAGE_TAG .
+
+    # Container security starts here
+
+      - name: Snyk Container image Scan
+        id: snyk_container_scan
+        run: |
+          snyk container test --org=ekene95 --tags=dev,container  $REGISTRY/$IMAGE_NAME:$IMAGE_TAG --severity-threshold=high
         env:
           SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
         continue-on-error: true
 
-  sign-image:
-    needs: setup
-    runs-on: ubuntu-latest
-    steps:
-      - name: Install Cosign
-        uses: sigstore/cosign-installer@main
-
-      - name: Sign with Cosign (Digest-Based)
-        env:
-          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
-          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
-        run: |
-          cosign sign --yes --key env://COSIGN_PRIVATE_KEY $REGISTRY/$IMAGE_NAME@${{ needs.setup.outputs.digest }}
-
-      - name: Verify Signature
-        env:
-          COSIGN_PUBLIC_KEY: ${{ secrets.COSIGN_PUBLIC_KEY }}
-        run: |
-          cosign verify --key env://COSIGN_PUBLIC_KEY $REGISTRY/$IMAGE_NAME@${{ needs.setup.outputs.digest }}
-
-  zap-scan:
-    needs: setup
-    runs-on: ubuntu-latest
-    steps:
-      - name: OWASP ZAP Full Scan
-        uses: zaproxy/action-full-scan@v0.6.0
-        with:
-          target: 'https://03dd-105-113-58-100.ngrok-free.app/api/v1/users'
-          token: ${{ secrets.GITHUB_TOKEN }}
-          cmd_options: '-z "-config api.addheaders=true -config api.key=${ZAP_API_KEY}"'
-          issue_title: 'ZAP Security Scan Findings'
-          fail_action: false
-        env:
-          ZAP_API_KEY: ${{ secrets.API_KEY }}
-
-      - name: Upload ZAP Reports
-        if: always()
-        uses: actions/upload-artifact@v4
-        with:
-          name: zap-security-reports
-          path: |
-            report.html
-            report.md
-            report.json
-
-  monitor-and-fail:
-    needs: [security-scans, sign-image]
-    runs-on: ubuntu-latest
-    steps:
       - name: Snyk Container Monitor
         id: snyk_monitor_result
         run: |
-          SNYK_MONITOR_OUTPUT=$(snyk monitor --all-projects --org=ekene95)
-          ALL_SNYK_LINKS=$(echo "$SNYK_MONITOR_OUTPUT" | grep -o 'https://app.snyk.io/org/[^[:space:]]*')
-          FIRST_SNYK_LINK=$(echo "$ALL_SNYK_LINKS" | head -n 1)
-          echo "SNYK_MONITOR_URL=$FIRST_SNYK_LINK" >> $GITHUB_OUTPUT
+            SNYK_MONITOR_OUTPUT=$(snyk monitor --all-projects --org=ekene95)
+            ALL_SNYK_LINKS=$(echo "$SNYK_MONITOR_OUTPUT" | grep -o 'https://app.snyk.io/org/[^[:space:]]*')
+            FIRST_SNYK_LINK=$(echo "$ALL_SNYK_LINKS" | head -n 1)
+            echo "SNYK_MONITOR_URL=$FIRST_SNYK_LINK" >> $GITHUB_OUTPUT
         env:
           SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
 
       - name: Fail Build on Snyk Vulnerabilities
-        if: ${{ needs.security-scans.result == 'failure' }}
+        if:  ${{ steps.snyk_test.outcome == 'failure' || steps.snyk_code_test.outcome == 'failure' || steps.snyk_container_scan.outcome == 'failure' }}
         run: |
           echo "Snyk found vulnerabilities in the container image!"
           SNYK_MONITOR_URL="${{ steps.snyk_monitor_result.outputs.SNYK_MONITOR_URL }}"
@@ -142,4 +81,48 @@ jobs:
           else
             echo "Snyk monitor link could not be retrieved. Please check the 'Snyk Container Monitor' step logs."
           fi
-          exit 1 
+          exit 1
+      
+      #Software provenance starts here
+      - name: Install Cosign
+        uses: sigstore/cosign-installer@main
+
+      - name: Push Docker image and get digest
+        run: |
+          docker push $REGISTRY/$IMAGE_NAME:$IMAGE_TAG
+          # Extract digest (format: sha256:abc123...)
+          DIGEST=$(docker inspect --format='{{index .RepoDigests 0}}' $REGISTRY/$IMAGE_NAME:$IMAGE_TAG | cut -d'@' -f2)
+          echo "DIGEST=${DIGEST}" >> $GITHUB_ENV
+
+      - name: Sign with Cosign (Digest-Based)
+        env:
+          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
+          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
+        run: |
+          cosign sign --yes --key env://COSIGN_PRIVATE_KEY $REGISTRY/$IMAGE_NAME@$DIGEST
+
+      - name: Verify Signature
+        env:
+          COSIGN_PUBLIC_KEY: ${{ secrets.COSIGN_PUBLIC_KEY }}
+        run: |
+          cosign verify --key env://COSIGN_PUBLIC_KEY $REGISTRY/$IMAGE_NAME@$DIGEST
+      
+      - name: OWASP ZAP Full Scan
+        uses: zaproxy/action-full-scan@v0.6.0
+        with:
+          target: 'https://03dd-105-113-58-100.ngrok-free.app/api/v1/users'
+          token: ${{ secrets.GITHUB_TOKEN }}
+          cmd_options: '-z "-config api.addheaders=true -config api.key=${ZAP_API_KEY}"'
+          issue_title: 'ZAP Security Scan Findings'
+          fail_action: false  # Don't fail workflow on findings
+        env:
+          ZAP_API_KEY: ${{ secrets.API_KEY }}
+           # - name: Upload ZAP Reports
+        if: always()
+        uses: actions/upload-artifact@v4
+        with:
+          name: zap-security-reports
+          path: |
+            report.html
+            report.md
+            report.json
